"""
Export-safe level project model.

A `LevelProject` bundles everything a playable level consists of:

- `map.tmx` (the `TmxLevelMap` model);
- `map_properties.tmx` (level metadata + missions, `TmxProperties` model);
- English dialog files (`dialog_<id>.txt`, `house_dialog_<id>.txt`).

Projects can be created blank, duplicated from a shipped level, or re-opened
from a previous export. Exports always target a separate output folder laid
out exactly like the game tree, so a user can review the files and copy them
into `maps/` + `data/` manually. The exporter refuses to write into the
game's own `maps/` or `data/` folders.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from editor.tmx_model import TmxLevelMap, TmxProperties

DIALOG_FILE_PATTERN = re.compile(r"^(house_dialog|dialog)_(\w+)\.txt$")

#: Language folders always stubbed on export, even if game data moved.
FALLBACK_LANGUAGES = ("en",)

PLAYTEST_NOTE_NAME = "HOW_TO_INSTALL.txt"

PLAYTEST_NOTE = """This folder was generated by the level editor.

It mirrors the layout of the game repository:

  maps/{name}/map.tmx                          -> the level map
  data/<language>/maps/{name}/map_properties.tmx -> level metadata & missions
  data/<language>/maps/{name}/dialog_*.txt       -> event dialogs
  data/<language>/maps/{name}/house_dialog_*.txt -> house dialogs

The game runtime only loads levels named `level_<number>` from its own
`maps/` folder (levels 0 to 3). To install this level manually:

1. Pick the level slot to replace (for example `level_1`).
2. Back up the game's `maps/level_1/` and `data/<language>/maps/level_1/`.
3. Copy the content of `maps/{name}/` over `maps/level_1/`.
4. Copy the content of `data/<language>/maps/{name}/` over
   `data/<language>/maps/level_1/` for every language folder.

Non-English dialog files are English stubs: translate them in place if
needed. For a quick test run without installing, use the editor's
"Playtest" button instead.
"""


class ExportLocationError(Exception):
    """The requested export location would overwrite working game data."""


@dataclass
class ExportReport:
    written: list[Path] = field(default_factory=list)
    backups: list[Path] = field(default_factory=list)


class LevelProject:
    def __init__(
        self,
        repo_root: Path | str,
        name: str,
        level_map: TmxLevelMap,
        properties: TmxProperties,
        dialogs: dict[str, str] | None = None,
    ) -> None:
        self.repo_root = Path(repo_root).resolve()
        self.name = name
        self.map = level_map
        self.properties = properties
        #: English dialog files: file name -> full text content.
        self.dialogs: dict[str, str] = dict(dialogs or {})

    # -- Constructors ------------------------------------------------------

    @classmethod
    def create_blank(
        cls, repo_root: Path | str, name: str, width: int, height: int
    ) -> "LevelProject":
        repo_root = Path(repo_root).resolve()
        level_map = TmxLevelMap.create_blank(
            width, height, base_dir=repo_root / "maps" / name
        )
        return cls(
            repo_root,
            name,
            level_map,
            TmxProperties.create_default(level_name=name),
        )

    @classmethod
    def from_template(
        cls, repo_root: Path | str, template_folder: str, name: str
    ) -> "LevelProject":
        """Duplicate a shipped level (`maps/<template_folder>`) as a project."""
        repo_root = Path(repo_root).resolve()
        map_dir = repo_root / "maps" / template_folder
        data_dir = repo_root / "data" / "en" / "maps" / template_folder
        return cls._load(repo_root, name, map_dir, data_dir)

    @classmethod
    def open_export(
        cls, repo_root: Path | str, export_root: Path | str, name: str
    ) -> "LevelProject":
        """Re-open a previously exported project for further editing."""
        repo_root = Path(repo_root).resolve()
        export_root = Path(export_root)
        map_dir = export_root / "maps" / name
        data_dir = export_root / "data" / "en" / "maps" / name
        return cls._load(repo_root, name, map_dir, data_dir)

    @classmethod
    def _load(
        cls, repo_root: Path, name: str, map_dir: Path, data_dir: Path
    ) -> "LevelProject":
        level_map = TmxLevelMap.from_file(map_dir / "map.tmx")
        # The nominal home of the map stays inside the game tree so that
        # relative tileset references keep resolving.
        level_map.base_dir = repo_root / "maps" / name
        properties = TmxProperties.from_file(data_dir / "map_properties.tmx")
        dialogs = {}
        if data_dir.is_dir():
            for path in sorted(data_dir.iterdir()):
                if DIALOG_FILE_PATTERN.match(path.name):
                    dialogs[path.name] = path.read_text(encoding="utf-8")
        return cls(repo_root, name, level_map, properties, dialogs)

    # -- Dialog management ---------------------------------------------------

    @staticmethod
    def dialog_file_name(kind: str, index: str) -> str:
        return f"{kind}_{index}.txt"

    def dialog_indexes(self, kind: str) -> list[str]:
        """Indexes of existing dialog files of `kind` (dialog | house_dialog)."""
        indexes = []
        for file_name in self.dialogs:
            match = DIALOG_FILE_PATTERN.match(file_name)
            if match and match.group(1) == kind:
                indexes.append(match.group(2))
        return sorted(indexes, key=lambda index: (len(index), index))

    def next_dialog_index(self, kind: str) -> str:
        numbers = [
            int(index) for index in self.dialog_indexes(kind) if index.isdigit()
        ]
        return str(max(numbers) + 1 if numbers else 0)

    def create_dialog(self, kind: str, content: str | None = None) -> str:
        """Create a new dialog file; return its file name."""
        index = self.next_dialog_index(kind)
        file_name = self.dialog_file_name(kind, index)
        if content is None:
            content = (
                "New dialog title\n---\nFirst line of the dialog.\n"
                if kind == "dialog"
                else "First line of the house dialog.\n"
            )
        self.dialogs[file_name] = content
        return file_name

    @staticmethod
    def dialog_preview(kind: str, content: str) -> tuple[str, list[str]]:
        """
        Plain-text preview mirroring the runtime parsing: for `dialog_*` files
        the first line is the title and the second line is skipped; for
        `house_dialog_*` files every line is spoken text.
        """
        lines = content.splitlines()
        if kind == "dialog":
            title = lines[0] if lines else ""
            return title, lines[2:]
        return "", lines

    # -- Export ----------------------------------------------------------------

    def language_codes(self) -> tuple[str, ...]:
        data_dir = self.repo_root / "data"
        found = tuple(
            sorted(
                child.name
                for child in data_dir.iterdir()
                if child.is_dir() and (child / "maps").is_dir()
            )
        ) if data_dir.is_dir() else ()
        return found or FALLBACK_LANGUAGES

    def _check_export_root(self, output_root: Path) -> None:
        output_root = output_root.resolve()
        protected = [
            self.repo_root / "maps",
            self.repo_root / "data",
        ]
        for forbidden in protected:
            if output_root == forbidden or forbidden in output_root.parents or output_root in (self.repo_root,):
                raise ExportLocationError(
                    f"Refusing to export into the working game data: {output_root}"
                )

    def _write_file(
        self, path: Path, content: bytes, backup: bool, report: ExportReport
    ) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and backup:
            backup_path = path.with_name(path.name + ".bak")
            shutil.copy2(path, backup_path)
            report.backups.append(backup_path)
        path.write_bytes(content)
        report.written.append(path)

    def export(self, output_root: Path | str, backup: bool = False) -> ExportReport:
        """
        Write the level bundle below `output_root`, mirroring the game tree:
        `maps/<name>/map.tmx` and `data/<lang>/maps/<name>/...` for every
        language of the game. Non-English folders receive English stub
        content so the localization layout is predictable.
        """
        output_root = Path(output_root)
        self._check_export_root(output_root)
        report = ExportReport()

        map_bytes = self.map.to_bytes()
        self._write_file(
            output_root / "maps" / self.name / "map.tmx", map_bytes, backup, report
        )

        properties_bytes = self.properties.to_bytes()
        for language in self.language_codes():
            language_dir = output_root / "data" / language / "maps" / self.name
            self._write_file(
                language_dir / "map_properties.tmx", properties_bytes, backup, report
            )
            for file_name, content in sorted(self.dialogs.items()):
                self._write_file(
                    language_dir / file_name,
                    content.encode("utf-8"),
                    backup,
                    report,
                )

        note = PLAYTEST_NOTE.format(name=self.name)
        self._write_file(
            output_root / PLAYTEST_NOTE_NAME, note.encode("utf-8"), backup, report
        )
        return report

    # -- Playtest staging ----------------------------------------------------------

    def stage_for_playtest(self, staging_dir: Path | str) -> Path:
        """
        Write a flat, self-contained copy of the level into `staging_dir`.

        The game runtime resolves the level folder both against the working
        directory (for `map.tmx`) and against `data/<language>/` (for
        `map_properties.tmx` and dialogs); passing one absolute folder for
        both makes it load everything from the staging directory without any
        runtime change. Tileset references are rewritten to absolute paths so
        the map renders from anywhere.
        """
        staging_dir = Path(staging_dir).resolve()
        staging_dir.mkdir(parents=True, exist_ok=True)

        map_bytes = self.map.to_bytes()
        staged_map = TmxLevelMap.from_bytes(map_bytes, self.map.base_dir)
        root = staged_map._root
        for tileset in root.findall("tileset"):
            source = tileset.get("source")
            if source:
                resolved = (self.map.base_dir / source).resolve()
                tileset.set("source", str(resolved))
        (staging_dir / "map.tmx").write_bytes(staged_map.to_bytes())
        (staging_dir / "map_properties.tmx").write_bytes(self.properties.to_bytes())
        for file_name, content in self.dialogs.items():
            (staging_dir / file_name).write_text(content, encoding="utf-8")
        return staging_dir
